app/clients/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired, Email, Optional

class EditClient(Form):
    name = StringField('Company Name', validators=[InputRequired()])
    address = StringField('Address', validators=[InputRequired()])
    phone = StringField('Office Phone')
    note = StringField('Notes')
    submit = SubmitField()


class EditContact(Form):
    first_name = StringField('First Name', validators=[InputRequired()])
    last_name = StringField('Last Name', validators=[InputRequired()])
    position = StringField('Position', validators=[InputRequired()])
    main_email = StringField('Main Email', validators=[InputRequired(), Email()])
    main_phone = StringField('Main Phone', validators=[InputRequired()])
    secondary_email = StringField('Secondary Email', validators=[Optional(), Email()])
    secondary_phone = StringField('Secondary Phone', validators=[Optional()])
    submit = SubmitField()

app/magazines/forms.py
from flask_wtf import Form
from wtforms import StringField, SelectField, IntegerField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import InputRequired
from ..models import Client, User


def get_all_clients():
    return Client.query.filter_by(active=True).order_by(Client.name).all()


def get_all_sales():
    return User.query.filter_by(role_id=4).order_by(User.name).all()


class EditMag(Form):
    owner = QuerySelectField('Client', query_factory=get_all_clients, get_label='name',
                             validators=[InputRequired()])
    published = SelectField('Published', choices=[('not published', 'Not Published'), ('published', 'Published')])
    name = StringField('Magazine Name', validators=[InputRequired()])
    sales_person = QuerySelectField('Sales Person', query_factory=get_all_sales, get_label='name',
                                    validators=[InputRequired()])
    page_count = IntegerField('Page Count', validators=[InputRequired()])
    note = StringField('Notes')
    submit = SubmitField()

app/tasks/forms.py
from flask_wtf import Form
from wtforms import StringField, SelectField, DateField, TextAreaField, widgets, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField, QuerySelectField
from wtforms.validators import InputRequired, Optional
from ..models import User


def get_all_users():
    return User.query.order_by(User.name).all()


class MultiCheckboxField(QuerySelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class EditTask(Form):
    users = MultiCheckboxField('Assign To', query_factory=get_all_users, get_label='name',
                               validators=[InputRequired()])
    name = StringField('Task Name', validators=[InputRequired()])
    description = StringField('Description')
    due_date = DateField(format='%m/%d/%Y', validators=[Optional()])
    status = SelectField('Status', choices=[('active', 'Active'), ('road-blocked', 'Road Blocked'),
                                            ('finished', 'Finished'), ('inactive', 'Inactive')],
                         validators=[InputRequired()])
    comment = TextAreaField('Comment (Optional)')
    pages = MultiCheckboxField('Pages', get_label='number')
    submit = SubmitField()


class EditComment(Form):
    poster = QuerySelectField('Posted By', query_factory=get_all_users, get_label='name',
                              validators=[InputRequired()])
    posted_date = DateField(format='%m/%d/%Y', validators=[Optional()])
    text = TextAreaField('Body', validators=[InputRequired()])
    submit = SubmitField()

app/clients/__init__.py
from flask import Blueprint

clients = Blueprint('clients', __name__)

from . import views, errors

app/clients/views.py
from flask import render_template, flash, redirect, url_for, request
from flask.ext.login import login_required
from .. import db
from ..models import Client, Contact, Magazine
from . import clients
from .forms import EditClient, EditContact


@clients.route('/')
@login_required
def all_clients():
    clients = Client.query.filter_by(active=True).order_by(Client.name.asc()).all()

    return render_template('all_clients.html', clients=clients)


@clients.route('/<int:id>')
@login_required
def client(id):
    client = Client.query.get(id)

    if not client:
        flash('That client does not exist.')
        return redirect(url_for('.all_clients'))

    return render_template('client.html', client=client)


@clients.route('/add', methods=['GET', 'POST'])
@login_required
def add_client():
    form = EditClient()

    if form.validate_on_submit():
        client = Client.query.filter_by(name=form.name.data).first()

        if client is None:
            client = Client(name=form.name.data,
                            address=form.address.data,
                            note=form.note.data)

            db.session.add(client)
            db.session.commit()
            flash('Client successfully added.')
            return redirect(url_for('.client', id=client.id))

        else:
            flash('{} already exists.'.format(str(client)))

    return render_template('form.html', form=form)


@clients.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_client(id):
    client = Client.query.get(id)

    if client is not None:
        form = EditClient(obj=client)

        if form.validate_on_submit():
            client.name = form.name.data
            client.phone = form.phone.data
            client.address = form.address.data
            client.note = form.note.data

            db.session.add(client)
            db.session.commit()
            flash('Client successfully edited.')
            return redirect(url_for('.client', id=id))

        return render_template('form.html', form=form)

    flash('That client does not exist.')
    return redirect(url_for('.all_clients'))


@clients.route('/archive/client/<int:id>')
@login_required
def archive_client(id):
    client = Client.query.get(id)

    if client:

        magazines = Magazine.query.filter_by(owner=client)

        if magazines:
            for magazine in magazines:
                magazine.active = False
                db.session.commit()

                for task in magazine.tasks:
                    task.active = False
                    db.session.commit()

        client.active = False
        db.session.commit()
        flash('The client, any associated magazines and their tasks have been archived.')
        return redirect(url_for('.all_clients'))

    flash('No such client exists.')
    return redirect(url_for('.all_clients'))


@clients.route('/delete/<int:id>')
@login_required
def delete_client(id):
    client = Client.query.get(id)

    if client:
        magazines = Magazine.query.filter_by(owner=client).all()

        if magazines:
            for magazine in magazines:
                for task in magazine.tasks:
                    db.session.delete(task)
                    db.session.commit()

                db.session.delete(magazine)
                db.session.commit()

        db.session.delete(client)
        db.session.commit()
        flash('The client, associated magazines and tasks have been deleted.')
        return redirect(url_for('.all_clients'))

    flash('No such client exists.')
    return redirect(url_for('.all_clients'))


@clients.route('/<int:client_id>/add/contact', methods=['GET', 'POST'])
@login_required
def add_contact(client_id):
    form = EditContact()

    client = Client.query.get(client_id)

    if form.validate_on_submit():
        contact = Contact(first_name=form.first_name.data,
                          last_name=form.last_name.data,
                          name='{} {}'.format(form.first_name.data, form.last_name.data),
                          position=form.position.data,
                          main_email=form.main_email.data,
                          main_phone=form.main_phone.data,
                          company=client)

        if form.secondary_email.data:
            contact.secondary_email = form.secondary_email.data
        if form.secondary_phone.data:
            contact.secondary_phone = form.secondary_phone.data

        db.session.add(contact)
        db.session.commit()

        return redirect(url_for('.client', id=client.id))

    return render_template('form.html', form=form)


@clients.route('/edit/contact/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_contact(id):
    contact = Contact.query.get(id)

    if contact:
        form = EditContact(obj=contact)

        if form.validate_on_submit():
            contact.first_name = form.first_name.data
            contact.last_name = form.last_name.data
            contact.name = '{} {}'.format(form.first_name.data, form.last_name.data)
            contact.main_email = form.main_email.data
            contact.main_phone = form.main_phone.data

            if form.secondary_phone.data:
                contact.secondary_phone = form.secondary_phone.data

            if form.secondary_email.data:
                contact.secondary_email = form.secondary_email.data

            db.session.add(contact)
            db.session.commit()

            return redirect(url_for('.client', id=contact.company_id))

        return render_template('form.html', form=form)

    flash('No such contact exists.')
    return redirect(url_for('.all_clients'))


@clients.route('/delete/contact/<int:id>')
@login_required
def delete_contact(id):
    contact = Contact.query.get(id)

    if contact is not None:
        db.session.delete(contact)
        db.session.commit()

        return redirect(url_for('clients.client', id=request.args.get('client')))

    return redirect(url_for('clients.client', id=request.args.get('client')))

app/magazines/__init__.py
from flask import Blueprint

magazines = Blueprint('magazines', __name__)

from . import views, errors

app/magazines/views.py
from flask import render_template, flash, redirect, url_for
from flask.ext.login import login_required
from .. import db
from ..models import Magazine, Page, Task
from . import magazines
from .forms import EditMag
from datetime import datetime


@magazines.route('/')
@login_required
def all_magazines():
    magazines = Magazine.query.filter_by(active=True).order_by(Magazine.client_mag.asc()).all()

    return render_template('all_mags.html', magazines=magazines)


@magazines.route('/<int:id>')
@login_required
def magazine(id):
    mag = Magazine.query.get(id)

    if not mag:
        flash('That magazine does not exist')
        return redirect(url_for('.all_magazines'))

    return render_template('magazine.html', mag=mag)


@magazines.route('/add', methods=['GET', 'POST'])
@login_required
def add_magazine():
    form = EditMag()

    if form.validate_on_submit():
        mag = Magazine(name=form.name.data,
                       owner=form.owner.data,
                       sales_person=form.sales_person.data,
                       page_count=form.page_count.data,
                       client_mag='{} - {}'.format(form.owner.data, form.name.data),
                       note=form.note.data)

        db.session.add(mag)
        db.session.commit()

        id = mag.id

        count = 1

        while count < form.page_count.data + 1:
            page = Page(number=count, magazine_id=id)
            db.session.add(page)
            db.session.commit()
            count += 1

        flash('Magazine successfully added.')
        return redirect(url_for('.all_magazines'))

    return render_template('form.html', form=form)


@magazines.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_magazine(id):
    mag = Magazine.query.get(id)

    if mag is not None:
        form = EditMag(obj=mag)

        if form.validate_on_submit():
            mag.name = form.name.data
            mag.owner = form.owner.data
            mag.sales_person = form.sales_person.data
            mag.page_count = form.page_count.data
            mag.note = form.note.data
            mag.client_mag = '{} - {}'.format(mag.owner.name, mag.name)

            if form.published.data == 'published':
                mag.active = False
                mag.published = datetime.utcnow()

                for task in mag.tasks:
                    task.active = False
                    db.session.add(task)
                    db.session.commit()

            if mag.page_count != form.page_count.data:
                for page in mag.pages:
                    db.session.delete(page)
                    db.session.commit()

                id = mag.id

                count = 1

                while count < form.page_count.data + 1:
                    page = Page(number=count, magazine_id=id)
                    db.session.add(page)
                    db.session.commit()
                    count += 1

            db.session.add(mag)
            db.session.commit()
            flash('Magazine successfully edited.')
            return redirect(url_for('.magazine', id=id))

        return render_template('form.html', form=form)

    flash('That magazine does not exist.')
    return redirect(url_for('.all_magazines'))


@magazines.route('/archive/<int:id>')
@login_required
def archive_magazine(id):
    magazine = Magazine.query.get(id)

    if magazine:
        for task in magazine.tasks:
                    task.active = False
                    db.session.commit()

        flash("The magazine and its tasks have been archived.")
        return redirect(url_for('.all_magazines'))

    flash('No such magazine exists.')
    return redirect(url_for('.all_magazines'))


@magazines.route('/delete/magazine/<int:id>')
@login_required
def delete_magazine(id):
    magazine = Magazine.query.get(id)

    if magazine:
        for task in magazine.tasks:
            db.session.delete(task)
            db.session.commit()

        db.session.delete(magazine)
        db.session.commit()
        flash('The magazine and associated tasks have been deleted.')
        return redirect(url_for('.all_magazines'))

    flash('No such magazine exists.')
    return redirect(url_for('.all_magazines'))

app/tasks/__init__.py
from flask import Blueprint

tasks = Blueprint('tasks', __name__)

from . import views, errors

app/templates/all_clients.html
{% extends "base.html" %}

{% block pagetitle %}
  All Clients
{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">

      {% for client in clients %}

       {% include 'ind_client.html' %}

      {% endfor %}
      
    </div>
  </div>

{% endblock %}

app/templates/all_mags.html
{% extends "base.html" %}

{% block pagetitle %}
  All Magazines
{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">

      {% for mag in magazines %}

        {% include 'ind_magazine.html' %}

      {% endfor %}
      
    </div>
  </div>

{% endblock %}

app/templates/all_tasks.html
{% extends "base.html" %}

  {% block pagetitle %}
    All Tasks
  {% endblock %}

{% block content %}
<div class="container">

  {% for task in tasks %}
    {% include 'ind_task.html' %}
  {% endfor %}
    
</div>
{% endblock %}

app/templates/all_users.html
{% extends "base.html" %}

{% block pagetitle %}
  All Users
{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">

      {% for user in users %}

      <div class="col s12">
        <div class="card-panel accordion black-text">
          <div class="card-title">
            <i class="left material-icons toggle" style="cursor:pointer;">reorder</i>
            <a class="waves-effect waves-light btn right" href="{{ url_for('auth.edit_user', id=user.id) }}">Edit User</a>
            <h4><a href="{{ url_for('auth.user', id=user.id) }}">{{ user.name }}</a></h4>
          </div>
          <ul class="collapsible" data-collapsible="accordion">
              <li>
                  <div class="collapsible-header">
                      <h4>Tasks</h4>
                  </div>
                  <div class="collapsible-body">
                      {% for task in user.tasks %}
                        {% include 'ind_task.html' %}
                      {% endfor %}
                  </div>
              </li>
          </ul>

        </div>
      </div>

      {% endfor %}
      
    </div>
  </div>

{% endblock %}

app/templates/base.html
<html>
    <head>
        {% block meta %}
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="msapplication-tap-highlight" content="no">
            <meta name="description" content="Materialize is a modern responsive CSS framework based on Material Design by Google. ">
        {% endblock %}

        {% block styles %}
            <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='materialize.min.css') }}">
            <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='prism.css') }}">
            <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='ghpages-materialize.css') }}">
            <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
            <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Inconsolata">
            <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        {% endblock %}

        {% block scripts %}

            <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
            <script type="text/javascript" src="{{ url_for('static', filename='materialize.min.js') }}"></script>

            {{ moment.include_moment() }}
            <script>
            $(document).ready(function(){
                $(" .button-collapse").sideNav();
                $(".accordion .toggle").parent().siblings().hide();
                $(".accordion .toggle").on("click", function(e){
                    if ($(this).hasClass("shown")) {
                        $(this).removeClass("shown");
                        $(this).parent().siblings().slideUp();
                    } else {
                        $(this).addClass("shown");
                        $(this).parent().siblings().slideDown();
                    }
                });
            });

            </script>
        {% endblock %}

        <title>{% block title %}Management System{% endblock %}</title>

    </head>

<body>
    {% block nav %}
        <header>
            <nav class="top-nav">
            <div class="container">
              <div class="nav-wrapper">
                <a class="page-title">{% block pagetitle %}CDManager {% endblock%} </a>
              </div>
            </div>
          </nav>
          <div class="container">
            <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full"><i class="mdi-navigation-menu"></i></a>
          </div>
          <ul id="nav-mobile" class="side-nav fixed">
            <li class="logo"><a id="logo-container" href="http://materializecss.com/" class="brand-logo"><img src="http://customdesignmags.com/templates/theme1189/images/logo/logo.png" style="width:150px;"></a></li>
            <li class="bold"><a href="{{ url_for('magazines.all_magazines') }}" class="waves-effect waves-orange">Home</a></li>
            <li class="no-padding">
              <ul class="collapsible collapsible-accordion">
               <li class="bold"><a class="collapsible-header waves-effect waves-orange">My Tasks</a>
                  <div class="collapsible-body">
                    <ul>
                      <li class="bold"><a href="{{ url_for('tasks.my_tasks') }}" class="waves-effect waves-orange">My Tasks</a></li>
                      <li class="bold"><a href="{{ url_for('tasks.my_assignments') }}" class="waves-effect waves-orange">My Assignments</a></li>
                    </ul>
                  </div>
                </li>
                <li class="bold"><a class="collapsible-header waves-effect waves-orange">Clients</a>
                  <div class="collapsible-body">
                    <ul>
                      <li><a href="{{ url_for('clients.all_clients') }}">All Clients</a></li>
                      <li><a href="{{ url_for('clients.add_client') }}">Add Client</a></li>
                    </ul>
                  </div>
                </li>
                <li class="bold"><a class="collapsible-header  waves-effect waves-orange">Magazines</a>
                  <div class="collapsible-body">
                    <ul>
                      <li><a href="{{ url_for('magazines.all_magazines') }}">All Magazines</a></li>
                      <li><a href="{{ url_for('magazines.add_magazine') }}">Add Magazine</a></li>
                    </ul>
                  </div>
                </li>
                <li class="bold"><a class="collapsible-header  waves-effect waves-orange">Tasks</a>
                  <div class="collapsible-body">
                    <ul>
                      <li><a href="{{ url_for('tasks.all_tasks') }}">All Tasks</a></li>
                    </ul>
                  </div>
                </li>
                <li class="bold"><a class="collapsible-header  waves-effect waves-orange">Users</a>
                  <div class="collapsible-body">
                    <ul>
                      <li><a href="{{ url_for('auth.all_users') }}">All Users</a></li>
                      {% if current_user.is_authenticated() %}
                      {% if current_user.role.name == 'Admin' %}
                      <li><a href="{{ url_for('auth.add_user') }}">Add User</a></li>
                      {% endif %}
                      {% endif %}
                    </ul>
                  </div>
                </li>
              </ul>
            </li>
            <li class="bold"><a href="{{ url_for ('auth.logout') }}" class="waves-effect waves-orange">Sign Out</a></li>
          </ul>
        </header>
    {% endblock %}

    {% block body %}

        <main>
            {% for message in get_flashed_messages() %}
                <script>Materialize.toast('{{ message }}', 8000)</script>
            {% endfor %}

            {% block content %}

            {% endblock %}
        </main>

    {% endblock %}

</body>

app/templates/contact.html
<li>
  <div class="collapsible-header">{{ contact.name }}
      <a class="right" href="{{ url_for('clients.delete_contact', id=contact.id, client=contact.company.id) }}">X</a>
      <a class="right edit-button" href="{{ url_for('clients.edit_contact', id=contact.id) }}">Edit</a>
  </div>
  <div class="collapsible-body">

      <table>
          <tbody>
              <tr>
                  <td>Position: {{ contact.position }}</td>
              </tr>
              <tr>
                  <td>Main Email: <a href="mailto:{{ contact.main_email }}">{{ contact.main_email }}</a></td>
              </tr>
              <tr>
                  <td>Main Phone: {{ contact.main_phone }}</td>
              </tr>
              {% if contact.secondary_phone %}
              <tr>
                  <td>Secondary Phone: {{ contact.secondary_phone }}</td>
              </tr>
              {% endif %}
              {% if contact.secondary_email %}
              <tr>
                  <td>Secondary Email: {{ contact.secondary_email }}</td>
              </tr>
              {% endif %}
          </tbody>
      </table>
  </div>
</li>

app/templates/form.html
{% extends "base.html" %}
{% import "material/wtf.html" as wtf %}

{% block content %}
<div class="container">

    {{ wtf.quick_form(form, action="") }}

</div>

<script>
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });

$(document).ready(function() {
    $('select').material_select();
  });
</script>

{% endblock %}

app/templates/ind_comment.html
<div class="row">
    <div class="col s12">
      <div class="card-panel black-text {{ task.status }} grey lighten-3">
         <p>
             {% if current_user.role_id==1 %}
                <a class="right" href="{{ url_for('tasks.delete_comment', id=comment.id) }}">X</a>
                <a class="right edit-button" href="{{ url_for('tasks.edit_comment', id=comment.id) }}">Edit</a>
             {% endif %}
             Posted by <a href="{{ url_for('auth.user', id=comment.poster.id) }}">{{ comment.poster.name }}</a> {{ moment(timestamp=comment.posted_date,
            local=True).format('MMMM Do YYYY, h:mm a') }}
         </p>
            <p>{{ comment.text }}</p>
      </div>
    </div>
</div>

app/templates/ind_magazine.html
<div class="col s12">
  <div class="card-panel accordion black-text {{ mag.status }}">
    <div class="card-title" style="clear:both;">
      <i class="left material-icons toggle" style="cursor:pointer;">reorder</i>
      <a href="{{ url_for('magazines.edit_magazine', id=mag.id) }}" class="waves-effect waves-light btn right">Edit Magazine</a>
      <h4 class="grey-text text-darken-4"><a href="{{ url_for('clients.client', id=mag.owner.id) }}">{{ mag.owner }}</a><br>
          <a href="{{ url_for('magazines.magazine', id=mag.id) }}">{{ mag.name }}</a></h4>
    </div>
    <p>Page Count: {{ mag.page_count }}</p>
    <p>Contacts:
        <ul class="collapsible" data-collapsible="accordion">
            {% if clients %}
                  {% for contact in client.contacts %}
                    {% include 'contact.html' %}
                  {% endfor %}
            {% elif mag %}
                {% for contact in mag.owner.contacts %}
                    {% include 'contact.html' %}
                  {% endfor %}
            {% endif %}
        </ul>
    </p>
    <p>Notes: {{ mag.note }}</p>
    <a class="btn-floating btn-large waves-effect waves-light red right" href="{{ url_for('tasks.add_task', mag=mag.id) }}">
        <i class="material-icons">+</i></a>
  </div>
</div>

app/templates/ind_task.html
<div class="row">
  <div class="col s12">
    <div class="card-panel black-text {{ task.status }}">
      <div class="card-title">
        <a href="{{ url_for('tasks.edit_task', id=task.id) }}" class="waves-effect waves-light btn right">Edit Task</a>
        <h5><a href="{{ url_for('clients.client', id=task.magazine.owner.id) }}">{{ task.magazine.owner.name }}</a></h5>
        <h5><a href="{{ url_for('magazines.magazine', id=task.magazine.id) }}">{{ task.magazine.name }}</a></h5>
        <h5><a href="{{ url_for('tasks.task', id=task.id) }}">{{ task.name }}</a></h5>
      </div>

      <p>Assigned to: 
      {% if task.users %}
        {% for user in task.users %}
          <a href="{{ url_for('auth.user', id=user.id) }}">{{ user.name }}</a>
        {% endfor %}
      {% endif %}</p>
      <p>Due Date: {% if task.due_date %}
          {{ moment(timestamp=task.due_date, local=True).format('MMMM Do YYYY') }}
          {% endif %}
      </p>
      <p>Description: {{ task.description }}</p>
      <p>Pages: {% for page in task.pages %} {{ page.number }} {% endfor %}</p>
      <p>Comments:</p>
      {%  for comment in task.comments %}
          {% include 'ind_comment.html' %}
      {% endfor %}
    </div>
  </div>
</div>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <h1>Hello, you're now logged in.</h1>
    
</div>
{% endblock %}

app/templates/my_tasks.html
{% extends "base.html" %}

{% block pagetitle %}
    {{ user.name }} <a class="waves-effect waves-light btn blue" href="{{ url_for('auth.user', id=user.id) }}">Edit User</a>
{% endblock %}

{% block content %}
<div class="container">

    {% if request.path=='/tasks/my_tasks' %}

        <h3>My Tasks</h3>

        {% for task in user.tasks %}
            {% if task.active==True %}
                {% include 'ind_task.html' %}
            {% endif %}
        {% endfor %}

    {% endif %}

    {% if request.path=='/tasks/my_assignments' %}

        <h3>My Assigned Tasks</h3>

        {% for task in user.assignments %}
            {% if task.active==True %}
                {% include 'ind_task.html' %}
            {% endif %}
        {% endfor %}

    {% endif %}

</div>
{% endblock %}

app/templates/test.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    {{ test }}

</div>
{% endblock %}

app/templates/user.html
{% extends "base.html" %}

{% block pagetitle %}
    {{ user.name }} <a class="waves-effect waves-light btn blue" href="{{ url_for('auth.user', id=user.id) }}">Edit User</a>
{% endblock %}

{% block content %}
<div class="container">

  {% for task in user.tasks %}
    {% if task.active==True %}
        {% include 'ind_task.html' %}
    {% endif %}
  {% endfor %}

</div>
{% endblock %}